# Generated by Django 3.2.20 on 2023-10-19 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='companyModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_c', models.CharField(max_length=30, unique=True)),
                ('slug', models.CharField(max_length=30, unique=True)),
                ('price', models.IntegerField()),
            ],
            options={
                'verbose_name': 'company',
                'verbose_name_plural': 'companyes',
                'ordering': ('name_c',),
            },
        ),
        migrations.CreateModel(
            name='postBlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('best_acc', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='')),
                ('company', models.ManyToManyField(related_name='postblog', to='home.companyModels')),
            ],
            options={
                'verbose_name': 'blogpost',
                'ordering': ('best_acc',),
            },
        ),
    ]
